if __name__ == "__main__":
    a = list() 
    
    a.append('A1')
    a.append('bbbb')
    a.append('a2')
    a.append('b222')
    a.append('a')
    a.append('b')
    a.append('a')
    a.append('b')
    a.append('a')
    a.append('')
    a.append('ba')
    a.append('sdb')
    a.append('as')
    a.append('db')
    a.append('a')
    a.append('sdfa')
    a.append('sdf')
    a.append('a')
    a.append('va')
    a.append('sdf')
    print(a)